### ISSUE TITLE
ANSI colour control sequences show as garbage on Windows

### ISSUE THREAD

**Issue by tambry** [rbsec/dnscan#11]
On Windows neither CMD or PowerShell support ANSI colour control sequences.

![Screenshots showing ANSI control sequences not being interpreted by Powershell](https://user-images.githubusercontent.com/1827708/38805149-79ad2b1e-417d-11e8-8a8f-0d27727767b4.png)

PowerShell itself does somehow support colours, just not the ANSI colour control sequences. I bet there's a library that handles such things.

**Comment by rbsec** [comment]
Fixed in the immediate term by just removing coloured output on Windows. As you say, I'm sure there's a way to get colour in PowerShell (and probably even CMD), but given you're the first person to ask about this in a few years, there doesn't seem to be too many people using it in CMD/PowerShell.

One for the todo list.

~rbsec

**Comment by sagar2117** [comment]
I am getting this error in Kali linux after this fix:-

Traceback (most recent call last):
  File "./dnscan.py", line 123, in <module>
    class col:
  File "./dnscan.py", line 124, in col
    if sys.stdout.isatty() and platform.system() != "Windows":

So i have to undo the changes of this script to make it work.

**Comment by rbsec** [comment]
Whoops, fixed in the latest commit.

**Comment by sagar2117** [comment]
It is working fine now. :)
